### ISSUE TITLE
Call for Sponsorsページ

### ISSUE THREAD

**Issue by HansRobo** [OUXT-Polaris/HP#28]
http://webcache.googleusercontent.com/search?q=cache:Cc25SKvw9aUJ:robotx.osaka/call-for-sponsors/+&cd=1&hl=ja&ct=clnk&gl=jp

**Comment by HidetoNiwa** [comment]
#33 でENに関しては対応済み、JPに関しては未対応

**Comment by HidetoNiwa** [comment]
#34 で対応完了しました。
